export const TextConstants = {
  INVALID_EMAIL: 'Invalid email address',
  NAME_REQUIRED: 'Name is required',
  QUANTITY_REQUIRED: 'Quantity is required',
  CHECKOUT: 'Checkout',
  BUYER_INFORMATION: 'Buyer Information',
  FULL_NAME: 'Full Name',
  EMAIL_ADDRESS: 'Email Address',
  QUANTITY_1_10: 'Quantity (1-10)',
  PRICE_SUMMARY: 'Price Summary',
  TOTAL: 'Total',
  COMPLETE_PURCHASE: 'Complete Purchase',
  REFERENCE_NUMBER: 'Reference Number',
  BACK_TO_EVENTS: 'Back to Events',
  VIEW_FAVORITES: 'View Favorites',
  YOUR_TICKETS_HAVE_BEEN_CONFIRMED:
    'Your tickets have been confirmed. You will receive an email confirmation shortly.',
  PAYMENT_SUCCESSFUL: 'Payment Successful!',
  NO_EVENTS_FOUND: 'No events found',
  TRY_ADJUSTING_YOUR_SEARCH_OR_FILTERS_TO_FIND_MORE_EVENTS:
    'Try adjusting your search or filters to find more events.',
  CLEAR_FILTERS: 'Clear Filters',
  NO_EVENTS_AVAILABLE: 'No events available',
  THERE_ARE_NO_EVENTS_AVAILABLE_AT_THE_MOMENT_PLEASE_CHECK_BACK_LATER:
    'There are no events available at the moment. Please check back later.',
  REFRESH: 'Refresh',
  SEARCH_EVENTS: 'Search events...',
  EVENT_DETAILS: 'Event Details',
  JOIN_WAITLIST: 'Join Waitlist',
  GET_TICKETS: 'Get Tickets',
  SOLD_OUT: 'Sold Out',
  THIS_EVENT_IS_SOLD_OUT_YOU_CAN_JOIN_THE_WAITLIST:
    'This event is sold out. You can join the waitlist.',
  ERROR: 'Error',
  FAILED_TO_UPDATE_FAVORITE_STATUS: 'Failed to update favorite status',
  LIMITED_SPOTS: 'Limited Spots',
  AVAILABLE: 'Available',
  DATE: 'Date',
  TIME: 'Time',
  VENUE: 'Venue',
  ABOUT: 'About',
  SPEAKERS: 'Speakers',
  AVAILABILITY: 'Availability',
  SPOTS: 'Spots',
  REMAINING: 'Remaining',
  NO_FAVORITES_YET: 'No favorites yet',
  EVENTS_YOU_MARK_AS_FAVORITES_WILL_APPEAR_HERE_START_EXPLORING_AND_ADD_SOME_EVENTS_TO_YOUR_FAVORITES:
    'Events you mark as favorites will appear here. Start exploring and add some events to your favorites!',
  FAVORITES: 'Favorites',
};
